name: Cricket Auction Manager CI

on:
  push:
    branches:
      - auctionmanager
        
jobs:
  run-auction:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Cricket Auction Manager
        run: node playwright-testing-lab\auctionManager\app.js